apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  map-gen-settings.json: |
{{- if .Values.factorio.mapGenSettings }}
{{ toJson .Values.factorio.mapGenSettings | indent 4 }}
{{- end }}
  map-settings.json: |
{{- if .Values.factorio.mapSettings }}
{{ toJson .Values.factorio.mapSettings | indent 4 }}
{{- end }}
  server-settings.json: |
{{- if .Values.factorio.serverSettings }}
{{ toJson .Values.factorio.serverSettings | indent 4 }}
{{- end }}
  server-adminlist.json: |
{{- if .Values.factorio.serverAdminlist }}
{{ toJson .Values.factorio.serverAdminlist | indent 4 }}
{{- end }}
  server-banlist.json: |
{{- if .Values.factorio.serverBanlist }}
{{ toJson .Values.factorio.serverBanlist | indent 4 }}
{{- end }}
  server-whitelist.json: |
{{- if .Values.factorio.serverWhitelist }}
{{ toJson .Values.factorio.serverWhitelist | indent 4 }}
{{- end }}