apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Chart.Name }}-credentials
    creationPolicy: Owner
  data:
  - secretKey: gamePassword
    remoteRef:
      key: gamepies_factorio_game-password
  - secretKey: accountPassword
    remoteRef:
      key: gamepies_factorio_account-password