apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: factorio-udp
    nodePort: {{ .Values.ports.udp }}
    port: 34197
    protocol: UDP
    targetPort: 34197
  - name: factorio-tcp
    nodePort:  {{ .Values.ports.tcp }}
    port: 27015
    protocol: TCP
    targetPort: 27015
  selector:
    app: {{ .Release.Name }}